# Dockerfile for CPU-based builds
FROM python:3.11-slim

# Installing UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Directory
WORKDIR /app

# Copying project files
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN pip install --system -r pyproject.toml

# Exposing and publishing the port for Jupyter Lab
EXPOSE 8888
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]